config/routes.rb
Rails.application.routes.draw do
  resources :oscillators do
    collection do
      post 'tune'
    end
  end

  root 'oscillators#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/oscillator.rb
class Oscillator < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :null_session
    skip_before_action :verify_authenticity_token
end

app/controllers/oscillators_controller.rb
class OscillatorsController < ApplicationController
  before_action :set_oscillator, only: [:show, :edit, :update, :destroy]

  # GET /oscillators
  # GET /oscillators.json
  def index
    @oscillators = Oscillator.all
  end

  # GET /oscillators/1
  # GET /oscillators/1.json
  def show
  end

  # GET /oscillators/new
  def new
    @oscillator = Oscillator.new
  end

  # GET /oscillators/1/edit
  def edit
  end

  # POST /oscillators
  # POST /oscillators.json
  def create
    @oscillator = Oscillator.new(oscillator_params)

    respond_to do |format|
      if @oscillator.save
        format.html { redirect_to @oscillator, notice: 'Oscillator was successfully created.' }
        format.json { render :show, status: :created, location: @oscillator }
      else
        format.html { render :new }
        format.json { render json: @oscillator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /oscillators/1
  # PATCH/PUT /oscillators/1.json
  def update
    respond_to do |format|
      if @oscillator.update(oscillator_params)
        format.html { redirect_to @oscillator, notice: 'Oscillator was successfully updated.' }
        format.json { render :show, status: :ok, location: @oscillator }
      else
        format.html { render :edit }
        format.json { render json: @oscillator.errors, status: :unprocessable_entity }
      end
    end
  end

  def tune
    id = params[:id]
    param_name = params[:param_name]
    value = params[:value]
    oscillator = Oscillator.find(id)

    if oscillator.update_attribute(param_name, value)
      render json: { status: 200 }, status: 200
    else
      render json: { status: 400 }, status: 400
    end
  end

  # DELETE /oscillators/1
  # DELETE /oscillators/1.json
  def destroy
    @oscillator.destroy
    respond_to do |format|
      format.html { redirect_to oscillators_url, notice: 'Oscillator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_oscillator
      @oscillator = Oscillator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def oscillator_params
      params.require(:oscillator).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/oscillators_helper.rb
module OscillatorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jan17react</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    
    <%= javascript_pack_tag 'oscillators_pack' %>

  </head>

  <body  data-props="<%= Oscillator.all.as_json(only: [:id, :title, :frequency, :wave, :detune]).to_json %>">
    <%= yield %>
  </body>
</html>

app/views/oscillators/_form.html.erb
<%= form_with(model: oscillator, local: true) do |form| %>
  <% if oscillator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(oscillator.errors.count, "error") %> prohibited this oscillator from being saved:</h2>

      <ul>
      <% oscillator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/oscillators/edit.html.erb
<h1>Editing Oscillator</h1>

<%= render 'form', oscillator: @oscillator %>

<%= link_to 'Show', @oscillator %> |
<%= link_to 'Back', oscillators_path %>

app/views/oscillators/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Oscillators</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @oscillators.each do |oscillator| %>
      <tr>
        <td><%= oscillator.title %></td>
        <td><%= oscillator.frequency %></td>
        <td><%= oscillator.wave %></td>
        <td><%= oscillator.detune %></td>
        <td><%= link_to 'Show', oscillator %></td>
        <td><%= link_to 'Edit', edit_oscillator_path(oscillator) %></td>
        <td><%= link_to 'Destroy', oscillator, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Oscillator', new_oscillator_path %>

app/views/oscillators/new.html.erb
<h1>New Oscillator</h1>

<%= render 'form', oscillator: @oscillator %>

<%= link_to 'Back', oscillators_path %>

app/views/oscillators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @oscillator.title %>
</p>

<%= link_to 'Edit', edit_oscillator_path(@oscillator) %> |
<%= link_to 'Back', oscillators_path %>